### ISSUE TITLE
Add licence file and headers to the project

### ISSUE THREAD

**Issue by bvitaliyg** [DevSrSouza/svg-to-compose#7]
This includes having licence file in the root of the repo as well as having licence headers in each file.

The licence allows the tool to be used in commercial codebases and may be crucial for a lot of companies around. It's especially important now as Compose is being adopted by many for production.

**Comment by bvitaliyg** [comment]
I can open the PR, but I need to know which license is preferable for the project.

**Comment by DevSrSouza** [comment]
Sorry that took so long to me add a License, thanks for pointing out that was missing, my bad.
